### ISSUE TITLE
python-dnspython

### ISSUE THREAD

**Issue by andreasschulze** [croessner/opendkim-manage#2]
unter Debian gibt es python-dnspython ( 2.7 ) oder python3-dnspython.
Ich würde hier unter Debian python3-dnspython nehmen und auf dem SLES-Server eben die python2.7 Version.

Wenn OK, kannst Du dieses Ticket gleich wieder zu machen...

**Comment by croessner** [comment]
Code is python 2 only. Python 3 support is on the TODO for the future
