### ISSUE TITLE
ImportError: No module named dns.resolver

### ISSUE THREAD

**Issue by andreasschulze** [croessner/opendkim-manage#3]
root@danube:/opt/opendkim-manage# apt-get install --no-install-recommends python3-dnspython
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden NEUEN Pakete werden installiert:
  python3-dnspython
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 102 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 612 kB Plattenplatz zusätzlich benutzt.
Holen:1 http://ftp.debian.org/debian stretch/main amd64 python3-dnspython all 1.15.0-1 [102 kB]
Es wurden 102 kB in 0 s geholt (1.321 kB/s).
Vormals nicht ausgewähltes Paket python3-dnspython wird gewählt.
(Lese Datenbank ... 21610 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../python3-dnspython_1.15.0-1_all.deb ...
Entpacken von python3-dnspython (1.15.0-1) ...
python3-dnspython (1.15.0-1) wird eingerichtet ...

root@danube:/opt/opendkim-manage# src/opendkim-manage 
Traceback (most recent call last):
  File "src/opendkim-manage", line 39, in <module>
    import dns.resolver
ImportError: No module named dns.resolver

was mache ich falsch?

**Comment by croessner** [comment]
The current branch is python 2.6/2.7. Python 3 support is on the TODO for the future
