### ISSUE TITLE
some keys are not rotated

### ISSUE THREAD

**Issue by andreasschulze** [croessner/opendkim-manage#9]
I've a ldap structure like this:

dc=top
ou=domains,dc=top
dc=example1.test,ou=domains,dc=top
dc=example2.test,ou=domains,dc=top
dc=sub,dc=example2.test,ou=domains,dc=top

Keys for example2.test and sub.example2.test are not rotated

**Comment by andreasschulze** [comment]
to be more precise: in the example above only the second entry (the subdomain) was rotated.

**Comment by andreasschulze** [comment]
The fix run here since >2 months and rotations now works fine.
You could merge the change upstream but correct the [spelling error]( https://github.com/andreasschulze/opendkim-manage/commit/28e0653c7f9d48e7cabe2a012c964a63d393376b#diff-954f25324c1afaa869d51ba9027cf80eR601)

**Comment by croessner** [comment]
Can you lease open a pull request for this?
